# BÀI TẬP

## Kiểm định đặc trưng tỉ lệ (p)

### Bài 1

Dataset 18 (__M&M__) chứa thông tin trọng lượng và màu sắc của mẫu các viên kẹo của hãng M&M. 

Sử dụng mẫu trên bạn hãy kiểm tra phát biểu sau: __"20% kẹo M&M có màu đỏ"__ với mức ý nghĩa là 5%

*Hướng dẫn: tính tỷ lệ các viên kẹo có màu đỏ từ dữ liệu, sử dụng kết quả để kiểm định phát biểu trên*

In [1]:
# import library
import numpy as np
from scipy.stats import norm
import math 
import pandas as pd

In [9]:
df = pd.read_excel('./data/18_M_M.xls')
df

      Red  Orange  Yellow  Brown   Blue  Green
0   0.751   0.735   0.883  0.696  0.881  0.925
1   0.841   0.895   0.769  0.876  0.863  0.914
2   0.856   0.865   0.859  0.855  0.775  0.881
3   0.799   0.864   0.784  0.806  0.854  0.865
4   0.966   0.852   0.824  0.840  0.810  0.865
5   0.859   0.866   0.858  0.868  0.858  1.015
6   0.857   0.859   0.848  0.859  0.818  0.876
7   0.942   0.838   0.851  0.982  0.868  0.809
8   0.873   0.863     NaN    NaN  0.803  0.865
9   0.809   0.888     NaN    NaN  0.932  0.848
10  0.890   0.925     NaN    NaN  0.842  0.940
11  0.878   0.793     NaN    NaN  0.832  0.833
12  0.905   0.977     NaN    NaN  0.807  0.845
13    NaN   0.850     NaN    NaN  0.841  0.852
14    NaN   0.830     NaN    NaN  0.932  0.778
15    NaN   0.856     NaN    NaN  0.833  0.814
16    NaN   0.842     NaN    NaN  0.881  0.791
17    NaN   0.778     NaN    NaN  0.818  0.810
18    NaN   0.786     NaN    NaN  0.864  0.881
19    NaN   0.853     NaN    NaN  0.825    NaN
20    NaN   0.864     NaN    NaN  0.855    NaN
21    NaN   0.873     NaN    NaN  0.942    NaN
22    NaN   0.880     NaN    NaN  0.825    NaN
23    NaN   0.882     NaN    NaN  0.869    NaN
24    NaN   0.931     NaN    NaN  0.912    NaN
25    NaN     NaN     NaN    NaN  0.887    NaN
26    NaN     NaN     NaN    NaN  0.886    NaN

In [15]:
# Tính tỷ lệ màu đỏ từ dữ liệu
red_ratios = df['Red'].dropna()
red_ratio_mean = red_ratios.mean()

# Giả thuyết Ho: 20% kẹo M&M có màu đỏ
p_0 = 0.20

# Tính toán giá trị kiểm định z-score
z_score = (red_ratio_mean - p_0) / (np.std(red_ratios, ddof=1) / np.sqrt(len(red_ratios)))

# Tính toán p-value
p_value = 1 - norm.cdf(z_score)  

# In ra kết quả
print("Tỷ lệ các viên kẹo có màu đỏ từ dữ liệu mẫu:", red_ratio_mean)
print("Giá trị z-score:", z_score.round(4))
print("p-value:", p_value.round(4))

Tỷ lệ các viên kẹo có màu đỏ từ dữ liệu mẫu: 0.8635384615384615
Giá trị z-score: 41.5392
p-value: 0.0

In [70]:
# Kiểm tra xem có bác bỏ giả thuyết không
alpha = 0.05
if p_value < alpha:
    print("Reject null hypothesis: Tỷ lệ kẹo M&M có màu đỏ không phải là 20%.")
else:
    print("Fail to reject null hypothesis: Tỷ lệ kẹo M&M có màu đỏ có thể là 20%."

Không đủ bằng chứng để bác bỏ giả thuyết.

### Bài 2

Dataset 3 (__FRESH15__) chứa thông tin khảo sát những thay đổi về trọng lượng (weight - WT) và chỉ số khối của cơ thể (BMI) của sinh viên năm nhất tại một trường Đại Học. Thời điểm khảo sát là bắt đầu học kỳ (tháng 9 - SEP) và kết thúc học kỳ (tháng 4 - APR), các sinh viên được chọn ngẫu nhiên trong trường.

Sử dụng mẫu trên, hãy kiểm tra phát biểu:__"50% số sinh viên trong trường là nam"__ với mức ý nghĩa 50%

Các thuộc tính trong bộ dữ liệu:
- SEX: Giới tính
- WTSEP: trọng lượng đo vào tháng 9 (mới nhập học)
- WTAPR: trọng lượng đo vào tháng 4 (kết thúc năm học)
- BMISP: BMI tháng 9
- BMIAP: BMI tháng 4

In [3]:
df = pd.read_excel('./data/03_FRESH15.xls')
df

   SEX  WTSEP  WTAPR  BMISP  BMIAP
0    M     72     59  22.02  18.14
1    M     97     86  19.70  17.44
2    M     74     69  24.09  22.43
3    M     93     88  26.97  25.57
4    F     68     64  21.51  20.10
..  ..    ...    ...    ...    ...
62   M     65     71  22.51  24.45
63   M     75     82  23.69  25.80
64   F     42     49  15.08  17.74
65   M     74     82  22.64  25.33
66   M     94    105  36.57  40.86

[67 rows x 5 columns]

In [7]:
# Tính tỷ lệ nam sinh viên từ dữ liệu mẫu
male_count = df[df['SEX'] == 'M'].shape[0]
total_count = df.shape[0]
male_ratio = male_count / total_count

# Giả thuyết Ho: tỷ lệ nam sinh viên là 50%
p_0 = 0.50

# Tính toán giá trị z-score
z_score = (male_ratio - p_0) / np.sqrt(p_0 * (1 - p_0) / total_count)

# Tính toán p-value
p_value = 2 * (1 - norm.cdf(np.abs(z_score))) 

# In kết quả
print("Tỷ lệ nam sinh viên từ dữ liệu mẫu:", male_ratio)
print("Giá trị z-score:", z_score.round(4))
print("p-value:", p_value.round(4))

Tỷ lệ nam sinh viên từ dữ liệu mẫu: 0.47761194029850745
Giá trị z-score: -0.3665
p-value: 0.714

In [65]:
# Kiểm tra xem có bác bỏ giả thuyết không
alpha = 0.05
if p_value < alpha:
    print("Reject null hypothesis: Không có 50% số sinh viên trong trường là nam.")
else:
    print("Fail to reject null hypothesis: Có thể có 50% số sinh viên trong trường là nam.")

Có đủ bằng chứng để bác bỏ giả thuyết.

### Bài 3

Dataset 6(__BEARS__) chứa thông tin khảo sát ngẫu nhiên các con gấu trong một khu rừng.

Sử dụng mẫu trên, bạn hãy kiểm tra phát biểu: __"tỷ lệ gấu đực trong khu rừng là 50%""__ với mức ý nghĩa 90%.

Biết rằng thuộc tính SEX có hai giá trị: 1 - gấu đực, 2- gấu cái.

In [20]:
df = pd.read_excel('./data/06_BEARS.xls')
df

    AGE  MONTH  SEX  HEADLEN  HEADWTH  NECK  LENGTH  CHEST  WEIGHT
0    19      7    1     11.0      5.5  16.0    53.0   26.0      80
1    55      7    1     16.5      9.0  28.0    67.5   45.0     344
2    81      9    1     15.5      8.0  31.0    72.0   54.0     416
3   115      7    1     17.0     10.0  31.5    72.0   49.0     348
4   104      8    2     15.5      6.5  22.0    62.0   35.0     166
5   100      4    2     13.0      7.0  21.0    70.0   41.0     220
6    56      7    1     15.0      7.5  26.5    73.5   41.0     262
7    51      4    1     13.5      8.0  27.0    68.5   49.0     360
8    57      9    2     13.5      7.0  20.0    64.0   38.0     204
9    53      5    2     12.5      6.0  18.0    58.0   31.0     144
10   68      8    1     16.0      9.0  29.0    73.0   44.0     332
11    8      8    1      9.0      4.5  13.0    37.0   19.0      34
12   44      8    2     12.5      4.5  10.5    63.0   32.0     140
13   32      8    1     14.0      5.0  21.5    67.0   37.0     180
14   20      8    2     11.5      5.0  17.5    52.0   29.0     105
15   32      8    1     13.0      8.0  21.5    59.0   33.0     166
16   45      9    1     13.5      7.0  24.0    64.0   39.0     204
17    9      9    2      9.0      4.5  12.0    36.0   19.0      26
18   21      9    1     13.0      6.0  19.0    59.0   30.0     120
19  177      9    1     16.0      9.5  30.0    72.0   48.0     436
20   57      9    2     12.5      5.0  19.0    57.5   32.0     125
21   81      9    2     13.0      5.0  20.0    61.0   33.0     132
22   21      9    1     13.0      5.0  17.0    54.0   28.0      90
23    9      9    1     10.0      4.0  13.0    40.0   23.0      40
24   45      9    1     16.0      6.0  24.0    63.0   42.0     220
25    9      9    1     10.0      4.0  13.5    43.0   23.0      46
26   33      9    1     13.5      6.0  22.0    66.5   34.0     154
27   57      9    2     13.0      5.5  17.5    60.5   31.0     116
28   45      9    2     13.0      6.5  21.0    60.0   34.5     182
29   21      9    1     14.5      5.5  20.0    61.0   34.0     150
30   10     10    1      9.5      4.5  16.0    40.0   26.0      65
31   82     10    2     13.5      6.5  28.0    64.0   48.0     356
32   70     10    2     14.5      6.5  26.0    65.0   48.0     316
33   10     10    1     11.0      5.0  17.0    49.0   29.0      94
34   10     10    1     11.5      5.0  17.0    47.0   29.5      86
35   34     10    1     13.0      7.0  21.0    59.0   35.0     150
36   34     10    1     16.5      6.5  27.0    72.0   44.5     270
37   34     10    1     14.0      5.5  24.0    65.0   39.0     202
38   58     10    2     13.5      6.5  21.5    63.0   40.0     202
39   58     10    1     15.5      7.0  28.0    70.5   50.0     365
40   11     11    1     11.5      6.0  16.5    48.0   31.0      79
41   23     11    1     12.0      6.5  19.0    50.0   38.0     148
42   70     10    1     15.5      7.0  28.0    76.5   55.0     446
43   11     11    2      9.0      5.0  15.0    46.0   27.0      62
44   83     11    2     14.5      7.0  23.0    61.5   44.0     236
45   35     11    1     13.5      8.5  23.0    63.5   44.0     212
46   16      4    1     10.0      4.0  15.5    48.0   26.0      60
47   16      4    1     10.0      5.0  15.0    41.0   26.0      64
48   17      5    1     11.5      5.0  17.0    53.0   30.5     114
49   17      5    2     11.5      5.0  15.0    52.5   28.0      76
50   17      5    2     11.0      4.5  13.0    46.0   23.0      48
51    8      8    2     10.0      4.5  10.0    43.5   24.0      29
52   83     11    1     15.5      8.0  30.5    75.0   54.0     514
53   18      6    1     12.5      8.5  18.0    57.3   32.8     140

In [21]:
# Tính tỷ lệ gấu đực từ dữ liệu mẫu
male_count = df[df['SEX'] == 1].shape[0]
total_count = df.shape[0]
male_ratio = male_count / total_count

# Giả thuyết Ho: Tỷ lệ gấu đực trong khu rừng là 50%
p_0 = 0.50

# Tính toán giá trị kiểm định z-score
z_score = (male_ratio - p_0) / np.sqrt((p_0 * (1 - p_0)) / total_count)

# Tính toán p-value
p_value = 1 - norm.cdf(z_score)  # one-tailed test

# In ra kết quả
print("Tỷ lệ gấu đực từ dữ liệu mẫu:", male_ratio)
print("Giá trị z-score:", z_score.round(4))
print("p-value:", p_value.round(4))

Tỷ lệ gấu đực từ dữ liệu mẫu: 0.6481481481481481
Giá trị z-score: 2.1773
p-value: 0.0147

In [22]:
# Kiểm tra xem có bác bỏ giả thuyết không
alpha = 0.10  # Mức ý nghĩa 90%
if p_value < alpha:
    print("Reject null hypothesis: Tỷ lệ gấu đực trong khu rừng không phải là 50%.")
else:
    print("Fail to reject null hypothesis: Tỷ lệ gấu đực trong khu rừng có thể là 50%.")

Reject null hypothesis: Tỷ lệ gấu đực trong khu rừng không phải là 50%.

### Bài 4

Dataset 9 __(MOVIES)__ chứa thông tin khảo sát một số phim trong khoảng thời gian 33 năm gần đây.

Có ý kiến cho rằng: __"55% các phim trong khoảng thời gian 33 năm gần đây có nhãn R (là phim giới hạn độ tuổi - Restricted)"__ .Theo bạn với mức ý nghĩa 95% ý kiến trên có đúng không?

Tham khảo: [Hệ thống phân loại của hiệp hội điện ảnh Mỹ](https://vi.wikipedia.org/wiki/H%E1%BB%87_th%E1%BB%91ng_ph%C3%A2n_lo%E1%BA%A1i_phim_c%E1%BB%A7a_MPAA#Ph%C3%A2n_lo%E1%BA%A1i_v%E1%BB%9Bi_c%C3%A1c_trailer_phim)

In [23]:
df = pd.read_excel('./data/09_MOVIES.xls')
df

,Title,MPAA,Budget,Gross,Length,Rating
0,8 Mile,R,41.0,117,110,6.7
1,Alone in the Dark,R,20.0,5,96,2.2
2,Aviator,PG-13,116.0,103,170,7.6
3,Big Fish,PG-13,70.0,66,125,8.0
4,Bourne Identity,PG-13,75.0,121,119,7.4
5,Break-Up,PG-13,52.0,116,105,5.8
6,Charlie's Angels: Full Throttle,PG-13,120.0,101,106,4.8
7,Collateral,R,65.0,100,120,7.7
8,Crash,R,6.5,55,113,8.3
9,Daddy Day Care,PG,60.0,104,92,5.7
10,DaVinci Code,PG-13,125.0,213,149,6.5
11,Eternal Sunshine of the Spotless Mind,R,20.0,34,108,8.6
12,From Justin to Kelly,PG,5.0,12,81,1.9
13,Harry Potter Goblet of Fire,PG-13,150.0,290,157,7.8
14,Hostel,R,4.5,47,94,5.8
15,House of the Dead,R,7.0,10,90,2.0
16,Last Samurai,R,100.0,111,154,7.8
17,Million Dollar Baby,PG-13,30.0,100,132,8.4
18,Pirates of the Carribbean (II),PG-13,225.0,322,150,7.5
19,Rollerball,PG-13,70.0,19,97,2.7
20,S.W.A.T.,PG-13,80.0,117,117,6.0
21,Secret Window,PG-13,40.0,48,96,6.3
22,Signs,PG-13,70.0,228,106,7.0
23,Silent Hill,R,50.0,47,127,6.6
24,Son of the Mask,PG,74.0,17,94,2.0
25,Spider-Man 2,PG-13,200.0,373,127,7.8
26,Star Wars III,PG-13,113.0,380,140,8.0
27,Sum of All Fears,PG-13,68.0,118,124,6.4
28,The Pianist,R,35.0,33,150,8.5
29,The Village,PG-13,72.0,114,108,6.6
30,Van Helsing,PG-13,160.0,120,132,5.3
31,Vanilla Sky,R,68.0,101,136,6.8
32,Walk the Line,PG-13,29.0,120,136,8.1
33,War of the Worlds,PG-13,132.0,234,116,6.7
34,Wedding Crashers,R,40.0,209,119,7.3

In [25]:
# Tính tỷ lệ phim có nhãn R từ dữ liệu mẫu
r_count = df[df['Rating'] == 'R'].shape[0]
total_count = df.shape[0]
r_ratio = r_count / total_count

# Giả thuyết Ho: 55% các phim trong khoảng thời gian 33 năm gần đây có nhãn R
p_0 = 0.55

# Tính toán giá trị kiểm định z-score
z_score = (r_ratio - p_0) / np.sqrt((p_0 * (1 - p_0)) / total_count)

# Tính toán p-value
p_value = 1 - norm.cdf(z_score)  # one-tailed test

# In ra kết quả
print("Tỷ lệ phim có nhãn R từ dữ liệu mẫu:", r_ratio)
print("Giá trị z-score:", z_score.round(4))
print("p-value:", p_value.round(4))

Tỷ lệ phim có nhãn R từ dữ liệu mẫu: 0.0
Giá trị z-score: -6.5405
p-value: 1.0

In [26]:
# Kiểm tra xem có bác bỏ giả thuyết không
alpha = 0.05  # Mức ý nghĩa 95%
if p_value < alpha:
    print("Reject null hypothesis: Tỷ lệ phim có nhãn R không phải là 55%.")
else:
    print("Fail to reject null hypothesis: Tỷ lệ phim có nhãn R có thể là 55%.")

Fail to reject null hypothesis: Tỷ lệ phim có nhãn R có thể là 55%.

## Kiểm định đặc trưng kỳ vọng ($\mu$) biết ($\sigma$)

### Bài 5

Dataset 13 __(VOLTAGE)__ liệt kê các mức điện áp được đo tại các hộ gia đình bởi các máy đo khác nhau: tại nhà (HOME), tại máy phát độc lập (Generator), tại trạm phát (UPS).

Công ty cung cấp điện cho vùng này cam kết rằng: __"Mục tiêu cung cấp điện cho mỗi hộ gia đình là 120V"__ . Biết rằng độ lệch chuẩn của tất cả các mức điện áp đo được là 0.24V.

Với mức ý nghĩa 1%. Bạn hãy kiểm tra xem công ty có làm đúng cam kết hay không?

In [27]:
df = pd.read_excel('./data/13_VOLTAGE.xls')
df

    Day   Home  Generator    UPS
0     1  123.8      124.8  123.1
1     2  123.9      124.3  123.1
2     3  123.9      125.2  123.6
3     4  123.3      124.5  123.6
4     5  123.4      125.1  123.6
5     6  123.3      124.8  123.7
6     7  123.3      125.1  123.7
7     8  123.6      125.0  123.6
8     9  123.5      124.8  123.6
9    10  123.5      124.7  123.8
10   11  123.5      124.5  123.7
11   12  123.7      125.2  123.8
12   13  123.6      124.4  123.5
13   14  123.7      124.7  123.7
14   15  123.9      124.9  123.0
15   16  124.0      124.5  123.8
16   17  124.2      124.8  123.8
17   18  123.9      124.8  123.1
18   19  123.8      124.5  123.7
19   20  123.8      124.6  123.7
20   21  124.0      125.0  123.8
21   22  123.9      124.7  123.8
22   23  123.6      124.9  123.7
23   24  123.5      124.9  123.8
24   25  123.4      124.7  123.7
25   26  123.4      124.2  123.8
26   27  123.4      124.7  123.8
27   28  123.4      124.8  123.8
28   29  123.3      124.4  123.9
29   30  123.3      124.6  123.8
30   31  123.5      124.4  123.9
31   32  123.6      124.0  123.9
32   33  123.8      124.7  123.9
33   34  123.9      124.4  123.9
34   35  123.9      124.6  123.6
35   36  123.8      124.6  123.2
36   37  123.9      124.6  123.1
37   38  123.7      124.8  123.0
38   39  123.8      124.3  122.9
39   40  123.8      124.0  123.0

In [38]:
# Độ lệch chuẩn đã cho
sigma = 0.24

# Trung bình mẫu
mean_voltage_home = df['Home'].mean()

# Số lượng quan sát
n = len(df)

# Giả thuyết Ho: Mức điện áp trung bình là 120V
mu_0 = 120

# Tính toán giá trị z-score
z_score = (mean_voltage_home - mu_0) / (sigma / np.sqrt(n))

# Tính toán p-value
p_value = 1 - norm.cdf(z_score)


# In ra kết quả
print("Trung bình mức điện áp tại nhà: {:.2f}V".format(mean_voltage_home))
print("Giá trị z-score: {:.2f}".format(z_score))
print("p-value: {:.6f}".format(p_value))

Trung bình mức điện áp tại nhà: 123.66V
Giá trị z-score: 96.52
p-value: 0.000000

In [39]:
# Mức ý nghĩa
alpha = 0.01

# Kiểm tra xem có bác bỏ giả thuyết không
if p_value < alpha:
    print("Bác bỏ giả thuyết Ho: Công ty không làm đúng cam kết.")
else:
    print("Không đủ bằng chứng để bác bỏ giả thuyết Ho: Công ty có thể đã làm đúng cam kết.")

Bác bỏ giả thuyết Ho: Công ty không làm đúng cam kết.

## Kiểm định đặc trưng kỳ vọng ($\mu$) không biết ($\sigma$)

### Bài 7

Dataset 19(__SCREWS__) chứa thông tin khảo sát chiều dài một số đinh ốc được cung cấp bởi công ty Crown Bolt (đơn vị inches)

Trên bao bì của các đinh ốc do công ty sản xuất có ghi chiều dài của các đinh ốc là 3/4 inches. Sử dụng mẫu trên bạn hãy cho biết chiều dài của đinh ốc lấy từ mẫu thu nhận được từ dữ liệu trên có nhất quán với chiều dài ghi trên bao bì hay không? Kiểm định với mức ý nghĩa 5%

In [40]:
df = pd.read_excel('./data/19_SCREWS.xls')
df

    0.757
0   0.723
1   0.754
2   0.737
3   0.757
4   0.741
5   0.722
6   0.741
7   0.743
8   0.742
9   0.740
10  0.758
11  0.724
12  0.739
13  0.736
14  0.735
15  0.760
16  0.750
17  0.759
18  0.754
19  0.744
20  0.758
21  0.765
22  0.756
23  0.738
24  0.742
25  0.758
26  0.757
27  0.724
28  0.757
29  0.744
30  0.738
31  0.763
32  0.756
33  0.760
34  0.768
35  0.761
36  0.742
37  0.734
38  0.754
39  0.758
40  0.735
41  0.740
42  0.743
43  0.737
44  0.737
45  0.725
46  0.761
47  0.758
48  0.756

In [50]:
# Giả thuyết Ho: Chiều dài trung bình của đinh ốc là 3/4 inches
mu_0 = 3/4

# Tính trung bình mẫu
sample_mean = df.mean()

# Tính độ lệch chuẩn mẫu
sample_std = np.std(df, ddof=1)

# Số lượng quan sát
n = len(df)

# Tính giá trị t-score
t_score = (sample_mean - mu_0) / (sample_std / np.sqrt(n))

# Tính p-value
p_value = norm.sf(np.abs(t_score)) * 2

# In kết quả
print("Trung bình mẫu của chiều dài đinh ốc:", round(sample_mean, 4), "inches")
print("Độ lệch chuẩn mẫu của chiều dài đinh ốc:", round(sample_std, 4), "inches")
print("Giá trị t-score:", round(t_score, 4))
print("p-value:", p_value)

Trung bình mẫu của chiều dài đinh ốc: 0.757    0.7466
dtype: float64 inches
Độ lệch chuẩn mẫu của chiều dài đinh ốc: 0.757    0.0124
dtype: float64 inches
Giá trị t-score: 0.757   -1.9185
dtype: float64
p-value: [0.05504245]

In [51]:
# Mức ý nghĩa
alpha = 0.05

# Kiểm tra xem có bác bỏ giả thuyết không
if p_value < alpha:
    print("Bác bỏ giả thuyết Ho: Chiều dài của đinh ốc không nhất quán với chiều dài ghi trên bao bì.")
else:
    print("Không đủ bằng chứng để bác bỏ giả thuyết Ho: Chiều dài của đinh ốc có thể nhất quán với chiều dài ghi trên bao bì.")

Không đủ bằng chứng để bác bỏ giả thuyết Ho: Chiều dài của đinh ốc có thể nhất quán với chiều dài ghi trên bao bì.

### Bài 8

Dataset 13 __(VOLTAGE)__ liệt kê các mức điện áp được đo tại các hộ gia đình bởi các máy đo khác nhau: tại nhà (HOME), tại máy phát độc lập (Generator), tại trạm phát (UPS).

Công ty cung cấp điện cho vùng này cam kết rằng: __"Mục tiêu cung cấp điện cho mỗi hộ gia đình là 120V"__ .

Với mức ý nghĩa 1%. Bạn hãy kiểm tra xem công ty có làm đúng cam kết hay không?

In [52]:
df = pd.read_excel('./data/13_VOLTAGE.xls')
df

    Day   Home  Generator    UPS
0     1  123.8      124.8  123.1
1     2  123.9      124.3  123.1
2     3  123.9      125.2  123.6
3     4  123.3      124.5  123.6
4     5  123.4      125.1  123.6
5     6  123.3      124.8  123.7
6     7  123.3      125.1  123.7
7     8  123.6      125.0  123.6
8     9  123.5      124.8  123.6
9    10  123.5      124.7  123.8
10   11  123.5      124.5  123.7
11   12  123.7      125.2  123.8
12   13  123.6      124.4  123.5
13   14  123.7      124.7  123.7
14   15  123.9      124.9  123.0
15   16  124.0      124.5  123.8
16   17  124.2      124.8  123.8
17   18  123.9      124.8  123.1
18   19  123.8      124.5  123.7
19   20  123.8      124.6  123.7
20   21  124.0      125.0  123.8
21   22  123.9      124.7  123.8
22   23  123.6      124.9  123.7
23   24  123.5      124.9  123.8
24   25  123.4      124.7  123.7
25   26  123.4      124.2  123.8
26   27  123.4      124.7  123.8
27   28  123.4      124.8  123.8
28   29  123.3      124.4  123.9
29   30  123.3      124.6  123.8
30   31  123.5      124.4  123.9
31   32  123.6      124.0  123.9
32   33  123.8      124.7  123.9
33   34  123.9      124.4  123.9
34   35  123.9      124.6  123.6
35   36  123.8      124.6  123.2
36   37  123.9      124.6  123.1
37   38  123.7      124.8  123.0
38   39  123.8      124.3  122.9
39   40  123.8      124.0  123.0

In [54]:
# Thiết lập giả thuyết H0: Mức điện áp trung bình là 120V
mu_0 = 120

# Tính trung bình mẫu và độ lệch chuẩn mẫu
sample_mean = df.mean()
sample_std = np.std(df, ddof=1)

# Số lượng quan sát
n = len(df)

# Tính giá trị t-score từ mẫu dữ liệu
t_score = (sample_mean - mu_0) / (sample_std / np.sqrt(n))

# Tính p-value
p_value = norm.sf(np.abs(t_score)) * 2

# In giá trị t-score và p-value
print("Giá trị t-score:", t_score)
print("p-value:", p_value)

Giá trị t-score: Day          -53.829677
Home          96.357841
Generator    102.091375
UPS           73.626368
dtype: float64
p-value: [0. 0. 0. 0.]

In [57]:
# Mức ý nghĩa
alpha = 0.01

# Kiểm tra xem có bác bỏ giả thuyết H0 hay không
if (p_value < alpha).any():
    print("Có bằng chứng để bác bỏ giả thuyết H0.")
else:
    print("Không có bằng chứng để bác bỏ giả thuyết H0.")

Có bằng chứng để bác bỏ giả thuyết H0.

### Bài 9

Dataset 2 __(BODYTEMP)__ chứa thông tin khảo sát nhiệt độ cơ thể từ một nhóm người vào cùng một thời điểm lúc 12h trưa.

Có một phát biểu nói rằng, nhiệt độ cơ thể người đo lúc 12h trưa trong quần thể này là 98,6°

Dựa vào mẫu trên, bạn hãy cho biết phát biểu trên đúng hay sai ở mức ý nghĩa là 5%.

In [59]:
df = pd.read_excel('./data/13_VOLTAGE.xls')
df

    Day   Home  Generator    UPS
0     1  123.8      124.8  123.1
1     2  123.9      124.3  123.1
2     3  123.9      125.2  123.6
3     4  123.3      124.5  123.6
4     5  123.4      125.1  123.6
5     6  123.3      124.8  123.7
6     7  123.3      125.1  123.7
7     8  123.6      125.0  123.6
8     9  123.5      124.8  123.6
9    10  123.5      124.7  123.8
10   11  123.5      124.5  123.7
11   12  123.7      125.2  123.8
12   13  123.6      124.4  123.5
13   14  123.7      124.7  123.7
14   15  123.9      124.9  123.0
15   16  124.0      124.5  123.8
16   17  124.2      124.8  123.8
17   18  123.9      124.8  123.1
18   19  123.8      124.5  123.7
19   20  123.8      124.6  123.7
20   21  124.0      125.0  123.8
21   22  123.9      124.7  123.8
22   23  123.6      124.9  123.7
23   24  123.5      124.9  123.8
24   25  123.4      124.7  123.7
25   26  123.4      124.2  123.8
26   27  123.4      124.7  123.8
27   28  123.4      124.8  123.8
28   29  123.3      124.4  123.9
29   30  123.3      124.6  123.8
30   31  123.5      124.4  123.9
31   32  123.6      124.0  123.9
32   33  123.8      124.7  123.9
33   34  123.9      124.4  123.9
34   35  123.9      124.6  123.6
35   36  123.8      124.6  123.2
36   37  123.9      124.6  123.1
37   38  123.7      124.8  123.0
38   39  123.8      124.3  122.9
39   40  123.8      124.0  123.0

In [66]:
# Thiết lập giả thiết
H0 = "Nhiệt độ cơ thể trung bình của quần thể là 98.6°F"
H1 = "Nhiệt độ cơ thể trung bình của quần thể khác 98.6°F"

# Số liệu mẫu
sample_mean = 98.2492
pop_mean = 98.6
sample_std = 0.7332
n = 130

# Tính giá trị t-score từ mẫu dữ liệu
t_score = (sample_mean - pop_mean) / (sample_std / (n ** 0.5))

# Tính p-value tương ứng với giá trị t-score tính được
p_value = 2 * (1 - norm.cdf(abs(t_score), n-1))

# In giá trị t-score và p-value
print("Giá trị t-score:", t_score)
print("p-value:", p_value)

Giá trị t-score: -5.455176474696795
p-value: 2.0

In [67]:
# Mức ý nghĩa
alpha = 0.05

# Kiểm tra xem có bác bỏ giả thuyết H0 hay không
if p_value < alpha:
    print("Bác bỏ giả thiết H0 và chấp nhận giả thiết H1: ", H1)
else:
    print("Không đủ bằng chứng để bác bỏ giả thiết H0: ", H0)

Không đủ bằng chứng để bác bỏ giả thiết H0:  Nhiệt độ cơ thể trung bình của quần thể là 98.6°F

### Bài 10

__FICO Score__ là đại lượng dùng để đo khả năng tín dụng của một cá nhân hoặc một tập thể. Sử dụng FICO Score, ngân hàng có thể quyết định xem có nên cho khách hàng mượn tiền hay không?

Dataset 24 __(FICO)__ chứa thông tin điểm tín dụng (FICO Score) của một số cá nhân trong vùng.

Sử dụng dữ liệu mẫu từ, bạn hãy cho biết ý kiến: __"điểm tín dùng trung bình của quần thể là 678"__ là đúng hay sai với mức ý nghĩa 5%

In [68]:
df = pd.read_excel('./data/24_FICO.xls')
df

    708
0   713
1   781
2   809
3   797
4   793
..  ...
94  796
95  611
96  709
97  697
98  732

[99 rows x 1 columns]

In [76]:
# Thiết lập giả thuyết H0: Điểm tín dụng trung bình của quần thể là 678
mu_0 = 678

# Số lượng quan sát
n = len(fico_scores)

# Tính trung bình mẫu và độ lệch chuẩn mẫu
sample_mean = np.mean(fico_scores)
sample_std = np.std(fico_scores, ddof=1)

# Tính giá trị t-score từ mẫu dữ liệu
t_score = (sample_mean - mu_0) / (sample_std / np.sqrt(n))

# Tính p-value
p_value = 2 * (1 - norm.cdf(abs(t_score), n-1))

# In giá trị t-score và p-value
print("Giá trị t-score:", t_score)
print("p-value:", p_value)

Giá trị t-score: 2.6899172359890855
p-value: 2.0

In [77]:
# Mức ý nghĩa
alpha = 0.05

# Kiểm tra xem có bác bỏ giả thuyết H0 hay không
if p_value < alpha:
    print("Bác bỏ giả thiết H0 và chấp nhận giả thiết H1: ", H1)
else:
    print("Không đủ bằng chứng để bác bỏ giả thiết H0: ", H0)

Không đủ bằng chứng để bác bỏ giả thiết H0:  Nhiệt độ cơ thể trung bình của quần thể là 98.6°F

---